apiVersion: v1
kind: Pod
metadata:
  name: memory-demo
  namespace: memory-example
spec:
  containers:
  - name: memory-demo-2-ctr
    image: polinux/stress
    resources:
      requests: #this is what will be allocated to pod 
        memory: "50Mi"
      limits: #this is the max size and if exceeded it will kill the node
        memory: "100Mi"
    command: ["stress"]
    args: ["--vm", "1", "--vm-bytes", "75M", "--vm-hang", "1"] #here we are stessing 250 