apiVersion: v1
kind: PersistentVolume
metadata:
  name: task-pv-volume
  labels:
    type: local
spec:
  storageClassName: standard
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath: #this is for the path of the node where the pvc will go 
    path: "/home/ubuntu/day28-storage-k8s"