apiVersion: v1
kind: Pod
metadata:
  name: task-pv-pod
spec:
  containers:
    - name: redis
      image: redis
      volumeMounts:
        - mountPath: "/data/redis"
          name: redis-storage
  volumes:
    - name: redis-storage
      emptyDir: {} #what this does is the volume inside the pod , and will exist till the pod is alive and not the container