apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nginx-deployment
  labels:
    env: demo
spec:
  template: #spec of the pod that it should be created , we don't need kind and apiVersion here
    metadata:
      labels:
        env: demo
        type: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
  selector: 
    matchLabels:
      env: demo