apiVersion: v1
kind: Pod
metadata:
  name: multi-container-pod
  labels:
    env: demo
spec:
  containers:
    - name: my-app-container
      image: busybox:1.28
      command: ['sh', '-c','echo the app is running && sleep 3600'] # How to pass the command and pass it with the arguments
      #The reason we say 3600 is so that the pod doest reach completed and will be in running state for 1 hour
      env:
        - name: FIRST_NAME
          value: "Rohan"
  initContainers:
    - name: init-myservice
      image: busybox:1.28
      command: ['sh', '-c'] # How to pass the command 
      args: ['until nslookup myservice.default.svc.cluster.local; do echo waiting for myservice to be up; sleep 2; done']
    - name: init-mydb #This will check if the service for the db is present 
      image: busybox:1.28
      command: ['sh', '-c'] # How to pass the command 
      args: ['until nslookup mydb.default.svc.cluster.local; do echo waiting for mydb to be up; sleep 2; done']
