apiVersion: batch/v1
kind: CronJob
metadata:
  name: chron-jod
  labels:
    env: day-12
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: chron-job
              image: busybox:1.28
              command: ['sh', '-c','echo 40daysofkubernetes']
          restartPolicy: Never

